server:
  port: 9000
---
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.jackson2: INFO
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
---
spring:
  datasource:
    url: jdbc:mysql://localhost/utiloauthorization?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: utiloauthorization
    password: utiloauthorization
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true