# In application.yml we define the active default profile.
# You can switch between profiles using this configuration.
spring:
  profiles:
    active: dev
# Authorization Server Version
utilo:
  version: 0.0.1